### ISSUE TITLE
커뮤니티, 팬채널 관련 API 구현

### ISSUE THREAD

**Issue by zeexzeex** [FANMIX-Works/FANMIX-BE#17]
## Tasks(Process)

- [x] 커뮤니티, 팬채널 리스트 정렬
- [x] 커뮤니티, 팬채널 게시글, 댓글 기능
- [x] 커뮤니티, 팬채널 상세정보

## References

- [link text] (link address)
