### ISSUE TITLE
CI/CD 설정

### ISSUE THREAD

**Issue by zoomin3022** [FANMIX-Works/FANMIX-BE#2]
## Description
CI 는 clean build 로
CD 는 AWS S3, CodeDeploy 로 구현

## Tasks(Process)

- [x] CI/CD yml 파일 생성
- [x] CodeDeploy 용 appspec.yml 생성
- [x] CodeDeploy 에서 실행할 스크립트 파일 생성
