### ISSUE TITLE
프로젝트 공통 설정 추가

### ISSUE THREAD

**Issue by zoomin3022** [FANMIX-Works/FANMIX-BE#3]
## Description
이미지 관리, 예외 관리, 공통 성공 실패 response, Swagger 처럼 프로젝트 공통적으로 필요한 설정 추가
추후에 fcm 등등 필요한것들도 추가되어야 함

## Tasks(Process)

- [x] AWS 관련 설정
- [x] 이미지 관리 설정
- [x] 예외 관리
- [x] 성공 실패 Response
- [x] Swagger 설정
